export const CROP_OPTIONS = [
  { name: 'Tomato', nameHindi: 'Tamatar', emoji: '🍅', category: 'Vegetables', avgPrice: 1200, trend: 'rising' as const, trendPercent: 15 },
  { name: 'Onion', nameHindi: 'Pyaaz', emoji: '🧅', category: 'Vegetables', avgPrice: 800, trend: 'falling' as const, trendPercent: 8 },
  { name: 'Potato', nameHindi: 'Aloo', emoji: '🥔', category: 'Vegetables', avgPrice: 900, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Wheat', nameHindi: 'Gehu', emoji: '🌾', category: 'Grains', avgPrice: 2150, trend: 'stable' as const, trendPercent: 3 },
  { name: 'Paddy', nameHindi: 'Dhan', emoji: '🌾', category: 'Grains', avgPrice: 2100, trend: 'rising' as const, trendPercent: 5 },
  { name: 'Maize', nameHindi: 'Makka', emoji: '🌽', category: 'Grains', avgPrice: 1400, trend: 'rising' as const, trendPercent: 7 },
  { name: 'Chickpea', nameHindi: 'Chana', emoji: '🫘', category: 'Pulses', avgPrice: 5200, trend: 'stable' as const, trendPercent: 1 },
  { name: 'Pigeon Pea', nameHindi: 'Tur/Arhar', emoji: '🫘', category: 'Pulses', avgPrice: 6800, trend: 'rising' as const, trendPercent: 6 },
  { name: 'Green Gram', nameHindi: 'Moong', emoji: '🫘', category: 'Pulses', avgPrice: 7200, trend: 'rising' as const, trendPercent: 4 },
  { name: 'Groundnut', nameHindi: 'Moongfali', emoji: '🥜', category: 'Cash Crops', avgPrice: 5500, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Soybean', nameHindi: 'Soyabin', emoji: '🌻', category: 'Cash Crops', avgPrice: 3900, trend: 'falling' as const, trendPercent: 5 },
  { name: 'Mustard', nameHindi: 'Sarson', emoji: '🌱', category: 'Cash Crops', avgPrice: 5200, trend: 'rising' as const, trendPercent: 8 },
  { name: 'Brinjal', nameHindi: 'Baingan', emoji: '🍆', category: 'Vegetables', avgPrice: 600, trend: 'falling' as const, trendPercent: 10 },
  { name: 'Cucumber', nameHindi: 'Kheera', emoji: '🥒', category: 'Vegetables', avgPrice: 500, trend: 'stable' as const, trendPercent: 3 },
  { name: 'Capsicum', nameHindi: 'Shimla Mirch', emoji: '🫑', category: 'Vegetables', avgPrice: 2000, trend: 'rising' as const, trendPercent: 12 },
  { name: 'Red Chilli', nameHindi: 'Lal Mirch', emoji: '🌶️', category: 'Spices', avgPrice: 8000, trend: 'rising' as const, trendPercent: 18 },
  { name: 'Garlic', nameHindi: 'Lahsun', emoji: '🧄', category: 'Spices', avgPrice: 12000, trend: 'rising' as const, trendPercent: 22 },
  { name: 'Ginger', nameHindi: 'Adrak', emoji: '🫚', category: 'Spices', avgPrice: 15000, trend: 'stable' as const, trendPercent: 4 },
  { name: 'Banana', nameHindi: 'Kela', emoji: '🍌', category: 'Fruits', avgPrice: 1200, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Grapes', nameHindi: 'Angoor', emoji: '🍇', category: 'Fruits', avgPrice: 3500, trend: 'rising' as const, trendPercent: 10 },
  { name: 'Orange', nameHindi: 'Santra', emoji: '🍊', category: 'Fruits', avgPrice: 2800, trend: 'stable' as const, trendPercent: 3 },
  { name: 'Lemon', nameHindi: 'Nimbu', emoji: '🍋', category: 'Fruits', avgPrice: 4000, trend: 'rising' as const, trendPercent: 8 },
  { name: 'Mango', nameHindi: 'Aam', emoji: '🥭', category: 'Fruits', avgPrice: 3000, trend: 'rising' as const, trendPercent: 15 },
  { name: 'Black Gram', nameHindi: 'Urad', emoji: '🫘', category: 'Pulses', avgPrice: 6500, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Millet', nameHindi: 'Bajra', emoji: '🌾', category: 'Grains', avgPrice: 2000, trend: 'stable' as const, trendPercent: 1 },
  { name: 'Sorghum', nameHindi: 'Jowar', emoji: '🌾', category: 'Grains', avgPrice: 2200, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Barley', nameHindi: 'Jau', emoji: '🌾', category: 'Grains', avgPrice: 1600, trend: 'stable' as const, trendPercent: 1 },
  { name: 'Fenugreek', nameHindi: 'Methi', emoji: '🌿', category: 'Spices', avgPrice: 3000, trend: 'stable' as const, trendPercent: 3 },
  { name: 'Coriander', nameHindi: 'Dhaniya', emoji: '🌿', category: 'Spices', avgPrice: 5000, trend: 'stable' as const, trendPercent: 4 },
  { name: 'Sesame', nameHindi: 'Til', emoji: '🫚', category: 'Cash Crops', avgPrice: 10000, trend: 'rising' as const, trendPercent: 6 },
  { name: 'Sunflower', nameHindi: 'Surajmukhi', emoji: '🌻', category: 'Cash Crops', avgPrice: 4200, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Cotton', nameHindi: 'Kapas', emoji: '🌿', category: 'Cash Crops', avgPrice: 6500, trend: 'stable' as const, trendPercent: 3 },
  { name: 'Sugarcane', nameHindi: 'Ganna', emoji: '🎋', category: 'Cash Crops', avgPrice: 380, trend: 'stable' as const, trendPercent: 0 },
  { name: 'Turmeric', nameHindi: 'Haldi', emoji: '🌿', category: 'Spices', avgPrice: 9000, trend: 'rising' as const, trendPercent: 12 },
  { name: 'Rice', nameHindi: 'Chawal', emoji: '🍚', category: 'Grains', avgPrice: 2100, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Cabbage', nameHindi: 'Patta Gobi', emoji: '🥬', category: 'Vegetables', avgPrice: 400, trend: 'falling' as const, trendPercent: 5 },
  { name: 'Cauliflower', nameHindi: 'Gobi', emoji: '🥦', category: 'Vegetables', avgPrice: 600, trend: 'stable' as const, trendPercent: 3 },
  { name: 'Okra', nameHindi: 'Bhindi', emoji: '🌿', category: 'Vegetables', avgPrice: 800, trend: 'rising' as const, trendPercent: 8 },
  { name: 'Carrot', nameHindi: 'Gajar', emoji: '🥕', category: 'Vegetables', avgPrice: 700, trend: 'stable' as const, trendPercent: 2 },
  { name: 'Watermelon', nameHindi: 'Tarbooz', emoji: '🍉', category: 'Fruits', avgPrice: 600, trend: 'rising' as const, trendPercent: 10 },
]

export const CROP_CATEGORIES = ['All', 'Vegetables', 'Grains', 'Fruits', 'Spices', 'Pulses', 'Cash Crops']

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
  'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
  'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Delhi', 'Jammu and Kashmir',
]
